services:
  db:
    image: postgres:15
    container_name: foodgram-db
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    container_name: foodgram-backend
    image: dafuqhappen/foodgram_backend:latest
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ./data:/app/data:ro

  frontend:
    container_name: foodgram-front
    image: dafuqhappen/foodgram_frontend:latest
    command: sh -lc 'rm -rf /app/result_build/* && cp -r /app/build/* /app/result_build/'
    volumes:
      - frontend_build:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html/
      - static:/static/
      - media:/media/

volumes:
  pg_data:
  static:
  media:
  frontend_build: