# Generated by Django 4.2.7 on 2025-08-01 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
    ]
